name: Project3 CI/CD

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-test:
    runs-on: self-hosted

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Show Docker version
        run: docker --version

      - name: Build application
        run: docker compose build

      - name: Start database and application
        run: docker compose up -d

      - name: Check containers
        run: docker compose ps

      - name: Check application
        run: |
          sleep 10
          curl -f http://127.0.0.1:8000 || exit 1

      - name: Stop application
        if: always()
        run: docker compose down
